version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - sudo service docker restart
      - docker build -t djdhar:ecs2 .
      - docker tag djdhar:ecs2 392417423125.dkr.ecr.us-east-1.amazonaws.com/djdhar_new_repo:latest
  post_build:
    commands:
      - docker push 392417423125.dkr.ecr.us-east-1.amazonaws.com/djdhar_new_repo:latest
      - printf '[{"name":"helloWorldNew","imageUri":"%s"}]' 392417423125.dkr.ecr.us-east-1.amazonaws.com/djdhar_new_repo:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
